[CI/CD] Update some requirements for the new version (#247)

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -15,10 +15,12 @@ RUN sed -i "s#\S\+#http://apt.ksyun.cn/ubuntu/#2" /etc/apt/sources.list && \
 ##############################################################################
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
+        software-properties-common build-essential autotools-dev \
+        nfs-common pdsh \
         curl wget vim tmux less unzip \
         htop iftop iotop ca-certificates openssh-client openssh-server \
-        rsync iputils-ping net-tools \
-        tzdata psmisc screen && \
+        rsync iputils-ping net-tools sudo \
+        tzdata psmisc screen libx11-dev llvm-dev && \
     apt-get clean
 
 ##############################################################################
@@ -30,6 +32,14 @@ RUN mkdir -p /run/sshd && \
     echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config
 
 ##############################################################################
+# Uninstall unnecessary packages and their dependencies
+##############################################################################
+RUN pip install pip-autoremove && \
+    pip-autoremove torch torchvision torchaudio torch-tensorrt \
+        pytorch-quantization pytorch-triton \
+        flash-attn transformer-engine tensorboard -y
+
+##############################################################################
 # Install Miniconda 
 ##############################################################################
 RUN mkdir -p ~/miniconda3 && \
@@ -38,3 +48,12 @@ RUN mkdir -p ~/miniconda3 && \
     rm -rf ~/miniconda3/miniconda.sh && \
     ~/miniconda3/bin/conda init bash || { echo 'conda init failed' ; exit 1; } && \
     ~/miniconda3/bin/conda config --set auto_activate_base false || { echo 'conda config failed' ; exit 1; }
+
+##############################################################################
+# Create Conda Environment and Install PyTorch
+##############################################################################
+SHELL ["bash", "-c"]
+RUN source ~/miniconda3/bin/activate && \
+    conda create -y --name flagscale python=3.10.12 && \
+    conda activate flagscale && \
+    conda install -y pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia || { echo 'PyTorch installation failed' ; exit 1; }
